name: Publish to PyPI

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel build twine

      - name: Build the package
        run: python3 -m build

      - name: Publish to PyPI using Trusted Publisher
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ""
        run: python3 -m twine upload --repository pypi dist/*
